fix airflow error non sense

diff --git a/source-code/build_deploy_flex_template.yaml b/source-code/build_deploy_flex_template.yaml
--- a/source-code/build_deploy_flex_template.yaml
+++ b/source-code/build_deploy_flex_template.yaml
@@ -73,16 +73,16 @@ steps:
     
   - id: "set-composer-variable"
     name: gcr.io/cloud-builders/gcloud
+    entrypoint: 'bash'
     args:
-      [
-        "composer",
-        "environments",
-        "update",
-        "${_COMPOSER_ENV_NAME}",
-        "--location",
-        "${_COMPOSER_REGION}",
-        "--update-env-variables=template_gcs_location_${_PIPELINE_NAME}=${_TEMPLATE_GCS_LOCATION},setup_file_${_PIPELINE_NAME}=/dataflow/template/data_pipeline/setup.py"
-      ]
+    - '-c'
+    - |
+      custom_comm=$(gcloud composer environments update ${_COMPOSER_ENV_NAME} --location ${_COMPOSER_REGION} --update-env-variables=template_gcs_location_${_PIPELINE_NAME}=${_TEMPLATE_GCS_LOCATION},setup_file_${_PIPELINE_NAME}=/dataflow/template/data_pipeline/setup.py --verbosity=debug 2>&1); \
+      echo "$custom_comm"; \
+      if [[ "$custom_comm" == *"ERROR: (gcloud.composer.environments.update) INVALID_ARGUMENT: No change in configuration. Must specify a change to configuration.software_configuration.env_variables"* ]]; then \
+        echo "This failure is expected if there is no change to env_variables"; exit 0; \ 
+      else exit 1; \
+      fi
 
     ######## TODO ADD INTEGRATION TEST
 
